In [1]:
import pandas as pd
import glob
import statsmodels.api as sm

In [ ]:
metric = "map" # map # ndcg_cut_10
result_format = "treceval" # treceval # ndcgeval

In [ ]:
results_df_list = []

for infile in glob.glob(f'./results/TRECDL2023/*.{result_format}'):
    judger = infile.split('/')[3].split('.')[2]
    result_df = pd.read_csv(infile, sep='\t', header=None, names=['run_id', 'metric', 'qid', 'score'])
    result_df = result_df[result_df['qid'] != 'all']
    result_df['metric'] = result_df['metric'].apply(lambda x: x.rstrip())
    result_df = result_df[(result_df['metric'] == metric)]
    result_df.drop(['metric'], axis=1, inplace=True)
    result_df['judged_by'] = judger
    result_df['qid'] = result_df['qid'].astype(int)
    result_df['score'] = result_df['score'].astype(float)
    results_df_list.append(result_df)
 
results_dfs = pd.concat(results_df_list)
results_dfs

In [ ]:
qid_to_info = pd.read_csv("infos/query_to_info.txt", sep='\t')
doc_to_info = pd.read_csv("infos/pass_to_info.txt", sep='\t')
model_to_info = pd.read_csv("infos/model_to_info.txt", sep='\t')

In [ ]:
data = pd.merge(results_dfs, qid_to_info, on='qid')
# data = pd.merge(data, doc_to_info, on='qid')
data = pd.merge(data, model_to_info, on='run_id')

In [ ]:
data.describe(include='object')
data

In [ ]:
mixed_model_int = (
"score ~ C(judged_by, Treatment(reference='nist')) * (QDR + QW + DL + isGPT4 + C(ST, Treatment(reference='Other')) + MN) "
)

In [ ]:
model_int = sm.MixedLM.from_formula(mixed_model_int, data, groups=data["run_id"])
result_int = model_int.fit()
result_int.summary()

# NDCG

In [2]:
metric = 'ndcg_cut_10'
result_format = 'ndcgeval'

In [3]:
results_df_list = []

for infile in glob.glob(f'./results/TRECDL2023/*.{result_format}'):
    judger = infile.split('/')[3].split('.')[2]
    result_df = pd.read_csv(infile, sep='\t', header=None, names=['run_id', 'metric', 'qid', 'score'])
    result_df = result_df[result_df['qid'] != 'all']
    result_df['metric'] = result_df['metric'].apply(lambda x: x.rstrip())
    result_df = result_df[(result_df['metric'] == metric)]
    result_df.drop(['metric'], axis=1, inplace=True)
    result_df['judged_by'] = judger
    result_df['qid'] = result_df['qid'].astype(int)
    result_df['score'] = result_df['score'].astype(float)
    results_df_list.append(result_df)
 
results_dfs = pd.concat(results_df_list)
results_dfs

                         run_id      qid   score judged_by
2                     cip_run_7  2001010  0.8563      nist
12                    cip_run_7  2001459  0.6551      nist
22                    cip_run_7  2001575  0.3321      nist
32                    cip_run_7  2002075  0.8087      nist
42                    cip_run_7  2002168  0.6691      nist
...                         ...      ...     ...       ...
28992  naverloo_bm25_splades_RR  3100825  0.7797      gpt4
29002  naverloo_bm25_splades_RR  3100833  0.8526      gpt4
29012  naverloo_bm25_splades_RR  3100909  0.9373      gpt4
29022  naverloo_bm25_splades_RR  3100918  0.9402      gpt4
29032  naverloo_bm25_splades_RR  3100922  0.7677      gpt4

[5740 rows x 4 columns]

In [4]:
qid_to_info = pd.read_csv("infos/query_to_info.txt", sep='\t')
doc_to_info = pd.read_csv("infos/pass_to_info.txt", sep='\t')
model_to_info = pd.read_csv("infos/model_to_info.txt", sep='\t')

In [5]:
data = pd.merge(results_dfs, qid_to_info, on='qid')
# data = pd.merge(data, doc_to_info, on='qid')
data = pd.merge(data, model_to_info, on='run_id')

In [6]:
data

,run_id,qid,score,judged_by,QL,QDR,QDS,QW,DL,Synthetic,isGPT4,ST,isLLM,MN
0,cip_run_7,2001010,0.8563,nist,0,0.7840,0.7023,6,72.5291,0,0,GPT,1,2
1,cip_run_7,2001459,0.6551,nist,0,2.6311,6.7917,4,57.2620,0,0,GPT,1,2
2,cip_run_7,2001575,0.3321,nist,0,0.1040,0.7523,4,440.2367,0,0,GPT,1,2
3,cip_run_7,2002075,0.8087,nist,0,1.8125,5.2791,7,1005.6332,0,0,GPT,1,2
4,cip_run_7,2002168,0.6691,nist,0,1.3110,4.3667,7,56.8986,0,0,GPT,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5735,naverloo_bm25_splades_RR,3100825,0.7797,gpt4,1,0.7835,4.0882,11,760.7758,1,1,T5,1,8
5736,naverloo_bm25_splades_RR,3100833,0.8526,gpt4,1,0.1144,0.6350,13,702.7082,1,1,T5,1,8
5737,naverloo_bm25_splades_RR,3100909,0.9373,gpt4,1,1.1883,2.7444,10,995.8028,1,1,T5,1,8
5738,naverloo_bm25_splades_RR,3100918,0.9402,gpt4,1,0.4276,2.0563,10,143.9186,1,1,T5,1,8
5739,naverloo_bm25_splades_RR,3100922,0.7677,gpt4,1,0.0383,0.5447,10,446.6774,1,1,T5,1,8

In [7]:
mixed_model_int = (
"score ~ C(judged_by, Treatment(reference='nist')) * (QDR + QW + DL + isGPT4 + C(ST, Treatment(reference='Other')) + MN) "
)

In [8]:
model_int = sm.MixedLM.from_formula(mixed_model_int, data, groups=data["run_id"])
result_int = model_int.fit()
result_int.summary()

/Users/saeed/anaconda3/lib/python3.11/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

<class 'statsmodels.iolib.summary2.Summary'>
"""
                                                  Mixed Linear Model Regression Results
==========================================================================================================================================
Model:                                        MixedLM                             Dependent Variable:                             score
No. Observations:                             5740                                Method:                                         REML
No. Groups:                                   35                                  Scale:                                          0.0419
Min. group size:                              164                                 Log-Likelihood:                                 827.2732
Max. group size:                              164                                 Converged:                                      Yes
Mean group size:                              164.0
------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                Coef.  Std.Err.   z    P>|z| [0.025 0.975]
------------------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                                        0.412    0.030 13.648 0.000  0.353  0.472
C(judged_by, Treatment(reference='nist'))[T.gpt4]                                                0.207    0.021  9.747 0.000  0.165  0.249
C(ST, Treatment(reference='Other'))[T.GPT]                                                      -0.076    0.039 -1.924 0.054 -0.153  0.001
C(ST, Treatment(reference='Other'))[T.T5]                                                        0.034    0.047  0.729 0.466 -0.058  0.127
C(ST, Treatment(reference='Other'))[T.T5+GPT]                                                    0.166    0.036  4.579 0.000  0.095  0.237
C(judged_by, Treatment(reference='nist'))[T.gpt4]:C(ST, Treatment(reference='Other'))[T.GPT]     0.018    0.016  1.140 0.254 -0.013  0.049
C(judged_by, Treatment(reference='nist'))[T.gpt4]:C(ST, Treatment(reference='Other'))[T.T5]      0.008    0.019  0.402 0.688 -0.030  0.045
C(judged_by, Treatment(reference='nist'))[T.gpt4]:C(ST, Treatment(reference='Other'))[T.T5+GPT]  0.003    0.015  0.219 0.827 -0.026  0.032
QDR                                                                                              0.033    0.003 10.498 0.000  0.026  0.039
C(judged_by, Treatment(reference='nist'))[T.gpt4]:QDR                                           -0.009    0.004 -1.972 0.049 -0.017 -0.000
QW                                                                                              -0.004    0.002 -2.311 0.021 -0.008 -0.001
C(judged_by, Treatment(reference='nist'))[T.gpt4]:QW                                             0.006    0.003  2.206 0.027  0.001  0.011
DL                                                                                              -0.000    0.000 -0.703 0.482 -0.000  0.000
C(judged_by, Treatment(reference='nist'))[T.gpt4]:DL                                            -0.000    0.000 -6.620 0.000 -0.000 -0.000
isGPT4                                                                                           0.059    0.013  4.575 0.000  0.034  0.085
C(judged_by, Treatment(reference='nist'))[T.gpt4]:isGPT4                                        -0.040    0.018 -2.174 0.030 -0.076 -0.004
MN                                                                                               0.019    0.008  2.402 0.016  0.003  0.034
C(judged_by, Treatment(reference='nist'))[T.gpt4]:MN                                             0.000    0.003  0.060 0.952 -0.006  0.006
Group Var                                                                                        0.006    0.008
==========================================================================================================================================

"""